global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway (Nginx)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Microserviço de Usuários
  - job_name: 'usuarios-api'
    static_configs:
      - targets: ['usuarios-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Microserviço de Funcionários
  - job_name: 'funcionarios-api'
    static_configs:
      - targets: ['funcionarios-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Microserviço de Solicitações de Reembolso
  - job_name: 'solicitacoes-api'
    static_configs:
      - targets: ['solicitacoes-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Microserviço de Relatórios
  - job_name: 'relatorios-api'
    static_configs:
      - targets: ['relatorios-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # SQL Server (se configurado com exporter)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sqlserver-exporter:9399']
    scrape_interval: 60s
    scrape_timeout: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health checks para todos os serviços
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'usuarios-api:8080'
        - 'funcionarios-api:8080'
        - 'solicitacoes-api:8080'
        - 'relatorios-api:8080'
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Blackbox exporter para monitoramento externo
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway/health
        - http://usuarios-api:8080/health
        - http://funcionarios-api:8080/health
        - http://solicitacoes-api:8080/health
        - http://relatorios-api:8080/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115